name: isSlimeChunk
version: '1.0.4'
main: com.zicstardust.isSlimeChunk.Main
api-version: '1.21.5'
author: zic_stardust
description: "Check if chunk spawn Slime"

default-permission: true

permissions:
  isSlimeChunk.slimechunk:
    description: "Permission command"

commands:
  slimechunk:
    description: "Check if chunk spawn Slime"
    usage: "/slimechunk"
    aliases: [isslimechunk, slimechunk]
    permission: isSlimeChunk.slimechunk
#    permission-message: "You do not have permission to use this command"