name: isSlimeChunk
version: '1.0.1'
main: com.zicstardust.isSlimeChunk.Main
api-version: '1.21.5'
author: zic_stardust
description: "Check if chunk spawn Slime"

#permissions:
#  permission.default:
#    description: "Not OP permission"
#    default: notop


commands:
  isSlimeChunk:
    description: "Check if chunk spawn Slime"
    usage: "/isSlimeChunk"
#    permission: permission.default
#    permission-message: "You do not have permission to use this command"